#!/bin/bash

set -o errexit
set -o pipefail

echo " => Creating Python virtual environment"
python3 -m venv venv

# shellcheck disable=SC1091
. venv/bin/activate

echo
echo " => Installing distribution tools"
pip install -q -U wheel twine

DEST_DIR="$(mktemp -d)/dist"
echo
echo " => Creating distribution in $DEST_DIR"
python setup.py sdist -d "$DEST_DIR" bdist_wheel -d "$DEST_DIR"

echo
echo " => Uploading package"
twine upload "$DEST_DIR/*"
